feat: u256 literals #22
auditless/suna pull request #24
Opened 2023-06-04 23:42 UTC by 0xd3bs

feat: u256 literals #22

2023-06-04 23:44 UTC, 0xd3bs commented
feat: u256 literals #22

2023-06-05 18:18 UTC, Pet3ris commented
Awesome PR

2023-06-05 18:19 UTC, Pet3ris requested changes
Need to just add a NumericLiteral trait

2023-06-06 16:58 UTC, Pet3ris approved these changes
LGTM

2023-06-06 16:58 UTC, merged